build: false

platform:
  - x86

install:
  - git submodule update --init --recursive
  - IF "%PLATFORM%" == "x86" set PATH=C:\Python37;%PATH%
  - IF "%PLATFORM%" == "x64" set PATH=C:\Python37-x64;%PATH%

test_script:
  - script\fetch-fixtures.cmd
  - python.exe setup.py --quiet test
