language: python

install:
  - pip install flake8

script:
  - script/fetch-fixtures
  - script/lint
  - script/test


matrix:
  include:
    - python: 3.5
    - python: 3.8
    - python: pypy3

branches:
  only:
    - master
