[build-system]
requires = ["setuptools>=43"]
build-backend = "setuptools.build_meta"

[project]
name = "tree-sitter"
version = "0.21.0"
description = "Python bindings for the Tree-Sitter parsing library"
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: C",
    "Programming Language :: Python",
    "Topic :: Software Development :: Compilers",
    "Topic :: Text Processing :: Linguistic",
    "Typing :: Typed"
]
requires-python = ">=3.8,<3.12"
readme = "README.md"

[project.urls]
Homepage = "https://tree-sitter.github.io/tree-sitter/"
Source = "https://github.com/tree-sitter/py-tree-sitter"

[[project.authors]]
name = "Max Brunsfeld"
email = "maxbrunsfeld@gmail.com"

[tool.ruff]
target-version = "py38"
line-length = 100
indent-width = 4
exclude = [
    ".git",
    ".github",
    ".venv",
    "build",
    "dist",
    "__pycache__",
    "tests/fixtures"
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.cibuildwheel]
build-frontend = "build"
test-command = "python -munittest discover -s {project}/tests"
environment = {PYTHONWARNINGS = "ignore:::tree_sitter"}
